config/routes.rb
Rails.application.routes.draw do
  resources :doodles do
    resources :members
  end
  root to: 'doodles#new'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/doodle.rb
class Doodle < ApplicationRecord

  has_many :members
  serialize :dates, Array
  has_secure_token

end

app/models/member.rb
class Member < ApplicationRecord

  belongs_to :doodle

  serialize :dates

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/doodles_controller.rb
class DoodlesController < ApplicationController
  before_action :set_doodle, only: [:show, :edit, :update, :destroy]


  # GET /doodles
  # GET /doodles.json
  def index
    @doodles = Doodle.all
  end

  # GET /doodles/1
  # GET /doodles/1.json
  def show
  end

  # GET /doodles/new
  def new
    @doodle = Doodle.new
    @creator = Member.new
  end

  # GET /doodles/1/edit
  def edit
  end

  # POST /doodles
  # POST /doodles.json
  def create
    @doodle = Doodle.new(doodle_params)

    respond_to do |format|
      if @doodle.save
        format.html { redirect_to doodle_path(@doodle.token), notice: 'Doodle was successfully created.' }
        format.json { render :show, status: :created, location: @doodle }
      else
        format.html { render :new }
        format.json { render json: @doodle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /doodles/1
  # PATCH/PUT /doodles/1.json
  def update
    respond_to do |format|
      if @doodle.update(doodle_params)
        format.html { redirect_to doodle_path(@doodle.token), notice: 'Doodle was successfully updated.' }
        format.json { render :show, status: :ok, location: @doodle }
      else
        format.html { render :edit }
        format.json { render json: @doodle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doodles/1
  # DELETE /doodles/1.json
  def destroy
    @doodle.destroy
    respond_to do |format|
      format.html { redirect_to doodles_url, notice: 'Doodle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doodle
      @doodle = Doodle.find_by_token(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def doodle_params
      params.require(:doodle).permit(:name, :location, :description, :creator, :dates => [])
    end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController

  before_action :set_doodle

  def create
    @member = Member.new(member_params)
    @member.doodle = @doodle

    respond_to do |format|
      if @member.save
        format.html { redirect_to doodle_path(@doodle.token), notice: 'Doodle was successfully created.' }
        format.json { render :show, status: :created, location: @doodle }
        format.js {render layout: false}
      else
        format.html { render :new }
        format.json { render json: @doodle.errors, status: :unprocessable_entity }
        format.js {render layout: false}
      end
    end
  end

  private

  def member_params
    params.require(:member).permit(:name, dates: [])
  end

  def set_doodle
    @doodle = Doodle.find_by_token(params[:doodle_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/doodles_helper.rb
module DoodlesHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/doodles/_form.slim
.row
  .col-md-12
    h3
      = yield(:page_title)
      |  doodle !
      - if @doodle.persisted?
        = link_to 'Voir le doodle', doodle_path(@doodle.token), class: "btn btn-info pull-right"

  .col-md-4
    .well
      .field
        = f.input :name
        = f.input :location
        = f.input :creator

        strong Nouvelle date
        .input-group
          input.form-control type="text" data-provide="datepicker" name="doodle_dates"
          span.input-group-btn
            button.btn.btn-success#addDate type="button"
              | Ajouter la date

        #hiddenDates.hide
          - @doodle.dates.each do |date|
            = hidden_field_tag "doodle[dates][]", date

        br
        strong Dates déjà proposées

        #proposedDates
          - @doodle.dates.each do |date|
            .proposed-date data-date=date
              | Le #{date}
              a.pull-right href='#'
                | Supprimer

        br
        - if false
          .input-group
            span.input-group-addon
              input type="checkbox"
            input.form-control type="text" value="32-09-2016"
          br
        = f.submit 'Save doodle !', class: "btn btn-success"

  .col-md-8
    = f.input :description


coffee:
  $("#addDate").on "click", (e) ->
    e.preventDefault()
    input = $("[name='doodle_dates']")
    if input.val() isnt ""
      alreadyExists = $("#hiddenDates input[value='#{input.val()}']").size() > 0
      unless alreadyExists
        hidden = $("<input type='hidden' name='doodle[dates][]' value='#{input.val()}'/>")
        $("#hiddenDates").append(hidden)
        date = $("<div class='proposed-date' data-date='#{input.val()}'>Le #{input.val()} <a class='pull-right' href='#'>Supprimer</a></div>")
        $("#proposedDates").append(date)

    input.val("")

  $(document).on "click", ".proposed-date a", (e) ->
    e.preventDefault()
    date = $(this).parent(".proposed-date").attr("data-date")
    $(this).parent(".proposed-date").remove()
    $("#hiddenDates input[value='#{date}']").remove()

app/views/doodles/edit.slim
br
- provide(:page_title, 'Edition')
= simple_form_for @doodle, url: doodle_path(@doodle.token) do |f|
 = render 'form', f: f

app/views/doodles/index.html.erb
<p id="notice"><%= notice %></p>

<div>
  <%= link_to 'New Doodle', new_doodle_path, class: 'btn btn-sm btn-success' %>
</div>
<br>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Location</th>
      <th>Creator</th>
      <th>Created at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @doodles.each do |doodle| %>
      <tr>
        <td><%= doodle.name %></td>
        <td><%= doodle.location %></td>
        <td><%= doodle.creator %></td>
        <td><%= doodle.created_at %></td>
        <td><%= link_to 'Show', doodle_path(doodle.token), class: 'btn btn-sm btn-primary' %></td>
        <td><%= link_to 'Edit', edit_doodle_path(doodle.token), class: 'btn btn-sm btn-warning' %></td>
        <td><%= link_to 'Destroy', doodle_path(doodle.token), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/doodles/new.slim
br
- provide(:page_title,'Creation')

= simple_form_for @doodle do |f|
  = render 'form', f: f

app/views/doodles/show.slim
p#notice = notice
.well.row
  h2.text-xs-center.col-md-12 = @doodle.name
  .col-md-5
    br
    p = "Created by #{@doodle.creator} "
    p = "Created at #{@doodle.created_at} "
    p = "Location #{@doodle.location} "
    p = "URL #{doodle_url(@doodle.token)} "
    = link_to 'Edit', edit_doodle_path(@doodle.token)
    hr.m-y-2
  .col-md-7
    h3
      = "Description of the doodle"
    p = @doodle.description.html_safe
  br
  .col-md-12
    table.table.table-hover#memberList
      thead.thead-default
        tr
          th.col-md-4 Members
          - @doodle.dates.each do |date|
            th.col-md-2 = date
          th
      tbody
        tr
          = simple_form_for Member.new, url: doodle_members_path(@doodle.token), remote: true do |f|
            td.col-md-4.freshline
              = f.input :name, label: false, input_html: {placeholder: 'Mr.Robot'}
            - @doodle.dates.each do |date|
              td.col-md-2
                input type="checkbox" value=date name="member[dates][]"
            td
              = f.submit "join !", class: 'btn btn-sm btn-success'
        - @doodle.members.each do |member|
          = render member

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to 'DouDeule !', root_path, class: 'navbar-brand' %>
      <ul class="nav navbar-nav">
        <li>
          <%= link_to 'Admin', doodles_path ,class: 'nav-link' %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Awesomedoodle</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
  </head>

  <body>
  <%= render 'layouts/navbar' %>
  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/members/_member.slim
tr
  td = member.name
  - @doodle.dates.each do |date|
    td.col-md-4
      - if member.dates.blank?
        span.glyphicon.glyphicon-remove
      - else
        - if member.dates.include? date
          span.glyphicon.glyphicon-ok
        - else
          span.glyphicon.glyphicon-remove
  td

app/views/members/create.js.erb
$('#memberList').append("<%= j render @member %>");